### PR TITLE
Update toolchain file to be compatible with paritytech/ci-linux Docker

### LINKED ISSUE #95: Docker Script is Broken
The Docker run script https://github.com/substrate-developer-hub/substrate-node-template/blob/master/scripts/docker_run.sh is suffering from a problem with the Rust nightly https://github.com/substrate-developer-hub/substrate-node-template/issues/90. It should use the nightly specified by the `rust-toolchain` file.

As reported by @anhcao142 https://github.com/substrate-developer-hub/substrate-node-template/issues/85#issuecomment-710107030

### PR DESCRIPTION
**Pull request by danforbes**
Thank you @TriplEight :pray: 

Closes #95

### CODE REVIEW

**Review by wheresaddie — APPROVED** [review]
:pray:

**Review by TriplEight — APPROVED** [review]
:+1:

**Comment by jeluard** [comment]
This apparently breaks the playground workflow: https://github.com/paritytech/substrate-playground/runs/1279340131?check_suite_focus=true#step:12:144
Not sure what's the real issue though.

**Comment by wheresaddie** [comment]
noooooooooooooooooooo .. seems like an incorrect reference to a file that is not present in the container @jeluard

**Comment by TriplEight** [comment]
@jeluard 's error `#9 0.139 error: invalid channel name 'stable-x86_64-unknown-linux-gnu' in '/home/playground/workspace/rust-toolchain'` is about stable toolchain name has to be more precise methinks. @danforbes

**Comment by wheresaddie** [comment]
.. https://github.com/rust-lang/rustup/issues/1745 ... :thinking:

**Comment by TriplEight** [comment]
yeah, when I was playing with it, it was failing in different weird ways

**Comment by wheresaddie** [comment]
likewise, Im not getting consistent issues, just a lot of them @TriplEight :/

**Comment by TriplEight** [comment]
I didn't find any good examples of how to mention more than one toolchan, nor the sane documentation for this declarative file. @danforbes  do you really need this file that much? What it does, it adds the mentioned toolchains to the ones already in the docker image.
`ci-linux` image has stable as default and nightly. Both have wasm32 target and a bunch of crates. To add a new toolchain, you'll have to prioritize it, or mention in every job i.e. `cargo +nightly-2020-10-10 check`. In this case `cargo +nightly check` will use another toolchain. I'd suggest having a script.

**Comment by jeluard** [comment]
`rust-toolchain` has been removed. It's content was incorrect anyway

**Pull request merged**
