### PR TITLE
V3.0.0+monthly 2021 09+1

### LINKED ISSUE #233: Update to `montly-2021-09` (and include patch for `prost v8`)
- [x] Use the flow from https://github.com/paritytech/substrate/blob/master/docs/node-template-release.md to go August->September 
- [x] https://github.com/paritytech/substrate/pull/9676 fixes #232 and will be included, a new tag with this cherry picked will be set from https://github.com/paritytech/substrate/tree/nukemandan/monthly-2021-09+1 (https://github.com/paritytech/substrate/commit/20a9bbb1fe47fcd62fcd64b2fa32456b4f434aaf)
- [ ] Update `latest` tag here to this patched release

### PR DESCRIPTION
**Pull request by NukeManDan**
Closes #233 
- [x] Tested locally to build with 
  ```
  rustc 1.54.0 (a178d0322 2021-07-26)
  rustc 1.57.0-nightly (e30b68353 2021-09-05)
  ```

### CODE REVIEW

**Comment by whereistejas** [comment]
I'm able to compile! It works for me.

**Review by sacha-l — COMMENTED** [review]
Nice to have you back @NukeManDan - works for me too. 🎉 

Just wondering, why are we doing `+1` at the end of the monthly tag?

**Comment by NukeManDan** [comment]
Glad to be back in action! 

The +1 indicates that this is a patch above the release. It includes the prost cherry pick to fix build issues not present in the monthly release

**Review by jimmychu0807 — APPROVED** [review]

**Comment by jimmychu0807** [comment]
@NukeManDan I am happy with the change and thanks for updating this. As Sacha mentioned, why the `+1` at the end of the monthly tag?

**Pull request merged**
