### PR TITLE
Additional package needed for Debian/Ubuntu/WSL

### PR DESCRIPTION
**Pull request by sameerdhoot**
In order to successfully build the template, we need to install the make tool which can be done independently. However, it is recommended to install a commonly needed essential package.

### CODE REVIEW

**Comment by NukeManDan** [comment]
We strive to be absolutely minimal in required packages. Make is not needed for anything in the template as described in the docs.substrate.io site either.

Am I missing something that does require it here?

**Comment by sameerdhoot** [comment]
Compiling futures-executor v0.3.21
   Compiling asynchronous-codec v0.6.0
error: failed to run custom build command for `tikv-jemalloc-sys v0.4.3+5.2.1-patched.2`

Caused by:
  process didn't exit successfully: `/home/nimda/dev/substrate-node-template/target/release/build/tikv-jemalloc-sys-b789a6952291f23f/build-script-build` (exit status: 101)
  --- stdout


…………………………..


  running: "make" "-j" "4"

  --- stderr
  thread 'main' panicked at 'failed to execute command: No such file or directory (os error 2)', /home/nimda/.cargo/registry/src/github.com-1ecc6299db9ec823/tikv-jemalloc-sys-0.4.3+5.2.1-patched.2/build.rs:334:19
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by muddlebee** [comment]
@NukeManDan I faced the same issue while installing in ubuntu WSL. and running the commands mentioned in this PR worked for me. 🎉

**Comment by sameerdhoot** [comment]
I changed the package from **build-essential** to **make** and it is tested and working on ubuntu 22.04 LTS and WSL2 on Windows 11

> We strive to be absolutely minimal in required packages. Make is not needed for anything in the template as described in the docs.substrate.io site either.
> 
> Am I missing something that does require it here?

**Review by NukeManDan — APPROVED** [review]

**Comment by NukeManDan** [comment]
From upstream docs PRs #1081 and #1026

**Pull request merged**
