### PR TITLE
Update to v2.0.0

### PR DESCRIPTION
**Pull request by danforbes**
cc @JoshOrndorff :tada:

### CODE REVIEW

**Review by jimmychu0807 — APPROVED** [review]
lgtm. Thanks for the short response time in updating the node template to v2.0.0

**Comment by wheresaddie** [comment]
awesome work @danforbes

**Comment by JoshOrndorff** [comment]
Awesome! Using crates.io too! Congrats!

**Comment by danforbes** [comment]
I knew you'd love that sweet, sweet `Cargo.toml` action, Joshy :wink:

**Pull request merged**
