### PR TITLE
Update to v2.0.1

### PR DESCRIPTION
**Pull request by danforbes**

### CODE REVIEW

**Comment by danforbes** [comment]
Replaces #118 and #125
Closes #108 #114 and #123

**Comment by danforbes** [comment]
I want to make sure that we do not move the tag for v2.0.1 once it is made, so please review this PR carefully and suggest anything you think should be added.

**Comment by jimmychu0807** [comment]
Hi,

- I went over @danforbes changes. I realized releasing node_template has a lot of manual work, and line-by-line comparison of 3 `Cargo.toml` files (node, runtime, and pallet_template) between ones generated by the script and what's in the node-template. They looks good. Thank for the work.

- I went over @NukeManDan changes. The replacement the `wasm-builder-runner` with `substrate-wasm-builder` looks good to me. Kudo to that. Removing specifying the nightly also looks good, as it runs now without the specification.

- I merge them all, and run `cargo build` and `cargo test`. They all passed.

- I made a minor link update and adding empty line in scripts.

Great effort guys! 🙌

Once you guys also confirm this is good, I think it is good for Dan to tag it as `v2.0.1`.

**Review by jimmychu0807 — APPROVED** [review]

**Comment by jimmychu0807** [comment]
close #128 as it is merged.

**Pull request merged**
