### PR TITLE
use substrate convention for editorconfig

### PR DESCRIPTION
**Pull request by NukeManDan**
https://www.npmjs.com/package/eclint used with substrate convention.

related to https://github.com/substrate-developer-hub/substrate-parachain-template/pull/42

### CODE REVIEW

**Comment by jimmychu0807** [comment]
@NukeManDan see if you want to close this PR. The code is outdated, having conflict with master, and to my understanding, no significant code change other than converting spacings to tabs.

**Comment by NukeManDan** [comment]
Correct, I can rebase. I think it's still needed. We just need to settle on what the standard should be. 🤷🏼

**Comment by NukeManDan** [comment]
https://github.com/paritytech/substrate/pull/8982

Now we can also include a ruatfmt file 🎉

**Comment by NukeManDan** [comment]
Closing in favor of #217 , but the .editorconfig IMHO should be included per https://github.com/paritytech/substrate/pull/9387

**Pull request closed without merging**
