### PR TITLE
remove space from manifest key  branch in all the cargo.toml files

### PR DESCRIPTION
**Pull request by jingnanzhou**
manifest key "branch" has a space in all the cargo.toml files.  it causes the branch info disabled

### CODE REVIEW

**Comment by NukeManDan** [comment]
This needs to be fixed in the ci generating this, not directly. 
 cc @sacha-l

**Comment by jingnanzhou** [comment]
@NukeManDan , where can I find ci code?

**Comment by NukeManDan** [comment]
Should be here https://github.com/paritytech/pipeline-scripts/blob/master/update_substrate_template.sh

**Comment by jingnanzhou** [comment]
I did not see the bug in following line: 
replace_ref="git = \"https:\/\/github.com\/paritytech\/$working_repo.git\", branch = \"${polkadot_branch}\""

The above code is from master branch. 
@NukeManDan @sacha-l

**Review by lisa-parity — APPROVED** [review]
Even if this needs to be done elsewhere. it needs to be fixed for people cloning this repo or everything breaks.

**Comment by lisa-parity** [comment]
@jingnanzhou @sacha-l @NukeManDan 
Maybe it should be:
replace_ref="git = "https://github.com/paritytech/$working_repo.git, branch = "${polkadot_branch}""
?
We **really** need this fixed in this repo ASAP, please. This manifest issue breaks stuff.

**Comment by NukeManDan** [comment]
@lisa-parity feel free to merge this PR as a fix, and any future critical ones. You don't need more than one approval here (yours) to move forward :pray: 

I am no longer actively maintaining this template, but I know the docs team absolutely should. I think @sacha-l said he would be willing to help? But identifying an owner is important.

**Comment by jingnanzhou** [comment]
@NukeManDan , @sacha-l , @lisa-parity 
I think there is a good potential to apply the template for an enterprise application, particularly in the financial industries. I am willing to be the template owner

**Review by melekes — APPROVED** [review]
👍

**Review by coderobe — APPROVED** [review]

**Comment by coderobe** [comment]
this was an issue in diener which has been fixed upstream (https://github.com/paritytech/diener/commit/0e35ce70f97cd6baa6aea129ed2edd0ee47304c7), so the fix should automatically trickle down to here once it's ran again

(for any future issues with the template generation, feel free to ping me or anyone else from parity release engineering)

**Comment by coderobe** [comment]
in the meantime, this can be merged as a temporary fix i think

**Comment by lisa-parity** [comment]
I don't have permission to merge here or I would have done so. Can someone with permission merge the fix?

**Comment by ggwpez** [comment]
Causing more issues… https://substrate.stackexchange.com/questions/6698  
@lisa-parity please ask someone to give you permissions.

**Review by ggwpez — APPROVED** [review]
Its fixed upstream in diener https://github.com/paritytech/diener/pull/31

**Comment by lisa-parity** [comment]
Thank you thank you thank you 👍 😀 !

**Comment by lisa-parity** [comment]
@coderobe, can we get this updated to use without quotes around "branch" like:
branch = "${polkadot_branch}"

and I'm wondering why the substrate-node-template has fallen behind and has `Cargo.toml` files referencing `0.9.35` instead of 36 or 37. I think we should be at 37, no?

**Pull request merged**
