### PR TITLE
Merge tag 'monthly-2021-11' into tutorials/solutions/permissioned-network-v3

### PR DESCRIPTION
**Pull request by fky2015**
This PR is done by merging the tag `monthly-2021-11' and tutorial's snippets.
Checked the correctness of the code by completing the [tutorial](https://docs.substrate.io/tutorials/v3/permissioned-network/).

### CODE REVIEW

**Comment by fky2015** [comment]
You can see the diff I brought in by `git diff monthly-2021-11..tutorials/solutions/permissioned-network-v3`.

**Comment by sacha-l** [comment]
@fky2015 - thanks for your help here! I can't seem to preview your commit without having the entire commit history since 9 months ago. Would you be able to fix this please?

**Comment by fky2015** [comment]
The target branch is somehow lagging about 9 months' commit. So it seems inevitable to have these commits when we try to catch up with the branch `monthly-2021-11`.

It seems the only way to see **what I brought in** is by **comparing this PR with branch `monthly-2021-11`**. ( As I said earlier `git diff monthly-2021-11..THIS-PR'S-BRANCH`) 

That's what I can come up with so far, do you have a better idea?

**Comment by sacha-l** [comment]
@fky2015 : Fixed this as part of a bigger endeavour for other tutorial solutions. Thanks for helping though, super appreciated ! 🙏🏻 

What I did was `git merge master` on the solution branch, fixed any conflicts, deleted all solution code and then made a [single commit](https://github.com/substrate-developer-hub/substrate-node-template/commit/d936239337922440aafaee6d50dbd5e086fe7e9c) to update it. It's actually pretty cool that you can see all the changes and optimizations done to the template since 9 months ago! 👀⚡️ Then, I added back the [solution code](https://github.com/substrate-developer-hub/substrate-node-template/commit/d3eaa1946d647b910a229ff7199f39d349a59e75) so that it's easier to see the diff. 🎉

**Pull request closed without merging**
